#!/bin/sh

# What can do for shell?
1. unit command.
sh="more test"
echo $sh, ls, cp, mv, head, tail, sed, awk,

2. pipe.
grep "hello" file.txt | wc -l
>
>>
tar -zcvf name.tar.gz `find . -mtime -1 -type f -print`

3. programming.
if [ -f "somefile" ]; then
elif ; then
else
fi

## Arrays
# How to initialize arrays
arrays=(alex bina cuc)
echo "The second is: ${arrays[1]}"

arrays[3]=da
echo "The four is: ${arrays[3]}"

# Get all member of arrays
echo "1-The all arrays is: ${arrays[*]}"
echo "2-The all arrays is: ${arrays[@]}"

# Get the size of arrays
echo "1-The all arrays is: ${#arrays[*]}"
echo "2-The all arrays is: ${#arrays[@]}"


## printf
# Example
printf "%-10s %-8s %-4s\n" Name Gender TMkg  
printf "%-10s %-8s %-4.2f\n" Alex Male 66.1234 
printf "%10s %8s %4.2f\n" Aluis Male 89.1234

printf "%d %s\n" 50 'string'
printf '%s %d %s\n' string1 89 "string2"
printf %s string

printf "%s\t" string1 string2 string3
printf %d 90

printf "a \123 string, no processing:<%s>\t\n\f" "A\nB"
printf "a \0003 string, no processing:<%b>\n" "A\nB"
printf "www.runoob.com \a" 


## test command
# 等于则为真 -eq -ne
# 大于则为真 -gt -ge
# 小于则为真 -lt le

num1=100
num2=100
if test $[num1] -eq $[num2]
then
    echo '两个数相等！'
else
    echo '两个数不相等！'
fi

# 字符串测试
# 等于/不等于则为真 =  ！=
# 字串长度为0为真	-z
# 字串长度不为0为真	-n
num1="ru1noob"
num2="runoob"
if test $num1 = $num2
then
    echo '两个字符串相等!'
else
    echo '两个字符串不相等!'
fi

# 文件测试
# 文件存在则为真 -e
cd /bin
if test -e ./bash
then
    echo '文件已存在!'
else
    echo '文件不存在!'
fi

# 逻辑控制
# 与 -a  或-o  非 ！
cd /bin
if test -e ./notFile -o -e ./bash
then
    echo '有一个文件存在!'
else
    echo '两个文件都不存在'
fi
