#!/bin/sh

# What can do for shell?
1. unit command.
sh="more test"
echo $sh, ls, cp, mv, head, tail, sed, awk,

2. pipe.
grep "hello" file.txt | wc -l
>
>>
tar -zcvf name.tar.gz `find . -mtime -1 -type f -print`

3. programming.
if [ -f "somefile" ]; then
elif ; then
else
fi

## Arrays
# How to initialize arrays
arrays=(alex bina cuc)
echo "The second is: ${arrays[1]}"

arrays[3]=da
echo "The four is: ${arrays[3]}"

# Get all member of arrays
echo "1-The all arrays is: ${arrays[*]}"
echo "2-The all arrays is: ${arrays[@]}"

# Get the size of arrays
echo "1-The all arrays is: ${#arrays[*]}"
echo "2-The all arrays is: ${#arrays[@]}"
